#!/bin/bash -e

echo "Build hook running"

C7N_VERSION=$(grep 'c7n==' requirements.txt | awk '{split($0,ary,"=="); print ary[2]}')

docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg C7N_VERSION=$C7N_VERSION \
             -f $DOCKERFILE_PATH \
             -t $IMAGE_NAME .
