#!/bin/bash -e

echo "Post-Push hook running"

# Ensure we also tag with the Cloud Custodian Version
if [ "$DOCKER_TAG" == 'latest' ]; then
	C7N_VERSION=$(grep 'c7n==' requirements.txt | awk '{split($0,ary,"=="); print ary[2]}')
	docker tag "$IMAGE_NAME" "${DOCKER_REPO}:${C7N_VERSION}"
	docker push "${DOCKER_REPO}:${C7N_VERSION}"
fi
